# Generated by Django 2.2.4 on 2020-04-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('mo_no', models.CharField(max_length=10)),
                ('cheapcomp', models.CharField(max_length=255)),
                ('associcomp', models.CharField(max_length=255)),
                ('allergy', models.CharField(max_length=255)),
                ('provisdigno', models.CharField(max_length=255)),
                ('treatment', models.CharField(max_length=255)),
                ('clinicalnotes', models.CharField(max_length=255)),
            ],
        ),
    ]
