# Generated by Django 3.0.5 on 2020-04-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='all_patients',
            table='all_patients',
        ),
    ]
