# Generated by Django 3.0.5 on 2020-04-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_auto_20200419_1824'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='all_patients',
            table=None,
        ),
    ]
