# Generated by Django 3.0.5 on 2020-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_auto_20200421_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_patients',
            name='clinicalnotes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
