# Generated by Django 3.0.5 on 2020-04-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_auto_20200422_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_patients',
            name='clinicalnotes',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
