# Generated by Django 3.0.5 on 2020-04-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0008_auto_20200422_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_patients',
            name='associcomp',
        ),
    ]
