# Generated by Django 3.0.5 on 2020-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0009_remove_all_patients_associcomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_patients',
            name='age',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
