# Generated by Django 3.0.5 on 2020-04-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0010_all_patients_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_patients',
            options={'get_latest_by': ['id']},
        ),
    ]
