# Generated by Django 3.0.5 on 2020-04-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0013_auto_20200430_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='old_patients',
            options={'get_latest_by': ['id']},
        ),
    ]
