# Generated by Django 3.0.5 on 2020-05-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0015_auto_20200430_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_patients',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200),
        ),
    ]
