# Generated by Django 3.0.5 on 2020-05-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0019_auto_20200505_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_patients',
            name='given_fee',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_patients',
            name='remaining_fee',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_patients',
            name='total_fee',
            field=models.IntegerField(default=33),
            preserve_default=False,
        ),
    ]
