# Generated by Django 3.0.5 on 2020-05-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0021_auto_20200505_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='old_patients',
            name='given_fee',
        ),
        migrations.RemoveField(
            model_name='old_patients',
            name='remaining_fee',
        ),
        migrations.RemoveField(
            model_name='old_patients',
            name='total_fee',
        ),
    ]
