# Generated by Django 3.0.5 on 2020-05-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0022_auto_20200505_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_patients',
            name='given_fee',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_patients',
            name='remaining_fee',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_patients',
            name='total_fee',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='old_patients',
            name='given_fee',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='old_patients',
            name='remaining_fee',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='old_patients',
            name='total_fee',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
