# Generated by Django 3.0.5 on 2020-05-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0024_all_patients_some'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_patients',
            name='some',
        ),
    ]
