# Generated by Django 3.0.5 on 2020-05-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0026_auto_20200506_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_patients',
            name='date',
            field=models.DateField(),
        ),
    ]
