# Generated by Django 3.0.5 on 2020-05-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0027_auto_20200506_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_patients',
            name='gender',
        ),
    ]
