# Generated by Django 3.0.5 on 2020-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0028_remove_all_patients_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_patients',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
