# Generated by Django 3.0.5 on 2020-05-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0030_auto_20200506_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_patients',
            name='given_fee',
        ),
        migrations.RemoveField(
            model_name='all_patients',
            name='remaining_fee',
        ),
        migrations.RemoveField(
            model_name='all_patients',
            name='total_fee',
        ),
        migrations.AlterField(
            model_name='all_patients',
            name='date',
            field=models.DateField(),
        ),
    ]
