# Generated by Django 3.0.5 on 2020-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0032_auto_20200507_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_patients',
            name='blood_press',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_patients',
            name='final_digno',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
