# Generated by Django 3.0.5 on 2020-05-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0033_auto_20200507_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_patients',
            name='blood_press',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='all_patients',
            name='final_digno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='old_patients',
            name='blood_press',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='old_patients',
            name='final_digno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
