# Generated by Django 3.0.5 on 2020-05-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0034_auto_20200508_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='old_patients',
            name='ipd',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='old_patients',
            name='parmanent_add',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='old_patients',
            name='parmanent_disease',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='old_patients',
            name='temporary_add',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
